name: grand_hotel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3  
  gap: ^3.0.1
  pinput: ^2.2.3
  calendar_date_picker2: ^2.0.1
  intl: ^0.20.2
  dotted_line: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/jost/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/jost/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/jost/Jost-Bold.ttf
          weight: 700
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/plusJakartaSans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/plusJakartaSans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/plusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700

